name: docker-ssh-failure-test

on: [push]

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6
        
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - name: Build container image
        run: docker build -t ${{ vars.REGISTRY}}/${{ vars.IMAGE_NAME}}:${{ steps.short-sha.outputs.sha }}  ./code
      
      - name: Run container (expect SSH failure)
        run: |
          set +e
          docker run --rm ssh-test \
            ssh -vvv \
              -o StrictHostKeyChecking=no \
              -o PasswordAuthentication=no \
              root@${{ secrets.HOST }}
          echo "exit code: $?"
