name: Deploy PROD

on:
  push:
    branches: [ main ]

jobs:  
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean registry
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ vars.REGISTRY }}/arimura-cj:latest .

      - name: Clean old images from registry
        run: |
          doctl registry repository list-tags arimura-cj \
            --no-header \
            --format Tag \
            --output text \
            | xargs -r -I {} doctl registry repository delete-tag arimura-cj {} --force || true
        
      - name: Push image to registry
        run: docker push ${{ vars.REGISTRY }}/arimura-cj:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin
            docker stop arimura-cj || true
            docker rm arimura-cj || true
            docker system prune -af
            docker pull ${{ vars.REGISTRY }}/arimura-cj:latest
            docker run -d \
              --restart always \
              --name arimura-cj \
              -p 5000:5000 \
              --env-file arimura_cj/.env \
              ${{ vars.REGISTRY }}/arimura-cj:latest