name: Deploy Server

on:
  push:
    branches:
      -main

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout Code
       uses: actions/checkout@v3

      -name: Build docoker image
       run: | 
         docker build -t arimura-cj-container:${{ github.sha }} .

      -name: Save docker image as tar
       run: | 
        docker save arimura-cj-container:${{ githut.sha }} -o arimura-cj-container.tar
        chmod 644 arimura-cj-container.tar

      -name: Copy docker image to droplet
       user: appleboy/scp-action@v0.1.7
       with:
         host: ${{secrets.HOST}}
         username: ${{secrets.USERNAME}}
         key: ${{secrets.KEY}
         source: arimura-cj-container.tar
         target: ~/images

      -name: Load the docker image run
       user: appleboy/ssh-action@v1.0.3
       with:
         host: ${{secrets.USERNAME}}
         username: ${{secrets.USERNAME}}
         key: ${{secrets.KEY}}
         script: |
           docker load -i /root/images/arimura-cj-container.tar
           docker rm -f arimura-cj-container
           docker run -d -p 8080:80  --name arimura-cj-container arimura-cj-container:${{github.sha}}
